export const s = {
  panel: { borderBottom: '1px solid #e5e7eb', flexShrink: 0 },
  header: {
    background: 'var(--colour-primary)',
    color: '#fff',
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    fontSize: '0.85rem',
    letterSpacing: '0.04em',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  collapseBtn: {
    width: 24,
    height: 24,
    border: '1px solid rgba(255,255,255,0.35)',
    borderRadius: 4,
    background: 'transparent',
    color: '#fff',
    cursor: 'pointer',
    fontSize: '1.1rem',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
    padding: 0,
    flexShrink: 0,
  },
  fields: {
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  fieldLabel: {
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.82rem',
    color: 'var(--colour-text)',
  },
  fieldHint: {
    fontWeight: 400,
    color: '#9ca3af',
  },
  input: {
    padding: '7px 10px',
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontSize: '0.88rem',
    color: 'var(--colour-text)',
    outline: 'none',
    width: '100%',
  },
  typeBadge: {
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#f7f2ff',
    color: 'var(--colour-primary)',
    padding: '8px 10px',
    fontFamily: 'var(--font-body)',
    fontSize: '0.86rem',
    fontWeight: 700,
  },
  addBtn: {
    padding: '7px 12px',
    background: 'var(--colour-primary)',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    fontFamily: 'var(--font-body)',
    fontWeight: 600,
    fontSize: '0.82rem',
    cursor: 'pointer',
    flexShrink: 0,
  },
  assetRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: '#f5f5f5',
    border: '1px solid #e5e7eb',
    borderRadius: 5,
    padding: '4px 8px',
  },
  assetPath: {
    flex: 1,
    fontFamily: 'var(--font-code)',
    fontSize: '0.78rem',
    color: 'var(--colour-text)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  divider: {
    height: 1,
    background: '#e5e7eb',
    margin: '4px 0',
  },
  stageGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 4,
  },
  stageBtn: {
    fontFamily: 'var(--font-body)',
    fontSize: '0.75rem',
    padding: '4px 8px',
    borderRadius: 5,
    border: '1px solid',
    cursor: 'pointer',
    transition: 'all 0.1s',
    letterSpacing: '0.02em',
  },
  removeBtn: {
    flexShrink: 0,
    background: 'none',
    border: 'none',
    color: '#ef4444',
    fontSize: '0.95rem',
    cursor: 'pointer',
    padding: '0 2px',
    lineHeight: 1,
  },
  assetSummary: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  storageSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '10px 12px',
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: 8,
  },
  storageTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  uploadAssetBtn: {
    color: '#16a34a',
    border: '1px solid #16a34a',
    padding: '4px 10px',
    fontSize: '0.78rem',
    whiteSpace: 'nowrap',
  },
  storageRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 5,
    padding: '4px 8px',
  },
  showInEditorLabel: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: '0.72rem',
    color: '#374151',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  copyUrlBtn: {
    flexShrink: 0,
    background: 'none',
    border: '1px solid #d1d5db',
    borderRadius: 4,
    color: '#6b7280',
    fontSize: '0.72rem',
    cursor: 'pointer',
    padding: '2px 6px',
  },
  assetBrowserInPanel: {
    maxHeight: 180,
    overflowY: 'auto',
  },
  sandboxSummary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    padding: '12px 14px',
    background: '#fff',
  },
  summaryText: {
    margin: '4px 0 0',
    fontFamily: 'var(--font-body)',
    fontSize: '0.82rem',
    color: '#6b7280',
    lineHeight: 1.45,
  },
  secondaryBtn: {
    color: 'var(--colour-primary)',
    border: '1px solid var(--colour-primary)',
    padding: '7px 12px',
    fontSize: '0.82rem',
    whiteSpace: 'nowrap',
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 40,
    background: 'rgba(17, 24, 39, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modal: {
    width: 'min(1120px, 94vw)',
    height: 'min(760px, 88vh)',
    background: '#fff',
    borderRadius: 8,
    boxShadow: '0 24px 70px rgba(0, 0, 0, 0.28)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  modalHeader: {
    height: 50,
    padding: '0 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #e5e7eb',
    background: '#fafafa',
    flexShrink: 0,
  },
  modalTitle: {
    fontFamily: 'var(--font-title)',
    fontWeight: 700,
    color: 'var(--colour-text)',
  },
  closeBtn: {
    width: 32,
    height: 32,
    border: '1px solid #e5e7eb',
    borderRadius: 6,
    background: '#fff',
    color: '#374151',
    cursor: 'pointer',
    fontSize: '1rem',
    lineHeight: 1,
  },
  modalBody: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    padding: 14,
  },
  modalEditor: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    width: '100%',
    display: 'flex',
  },
  htmlCodeEditor: {
    width: '100%',
    minWidth: 0,
    flex: '1 1 auto',
  },
  modalCodeEditor: {
    width: '100%',
    minWidth: 0,
    flex: '1 1 auto',
  },
  scratchSandboxShell: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  workspaceTabs: {
    display: 'inline-grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 4,
    alignSelf: 'flex-start',
    border: '1px solid #e5e7eb',
    borderRadius: 8,
    padding: 4,
    background: '#fff',
    flexShrink: 0,
  },
  scratchSandboxEditor: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    width: '100%',
    display: 'flex',
    overflow: 'hidden',
  },
  scratchConfigSidebar: {
    width: 300,
    flexShrink: 0,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    borderRight: '1px solid #e5e7eb',
    background: '#fafafa',
    padding: '12px 10px',
  },
  sidebarSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  sidebarSectionTitle: {
    fontFamily: 'var(--font-body)',
    fontWeight: 700,
    fontSize: '0.78rem',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    paddingBottom: 4,
    borderBottom: '1px solid #e5e7eb',
  },
  noFile: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#9ca3af',
    fontFamily: 'var(--font-body)',
    fontSize: '0.9rem',
  },
}
