// Python-side `turtle` module shim, prepended to student code (same technique as
// electronics' MICROPYTHON_SHIM in ../electronics/index.js): a plain array of
// Python source lines, joined and exec'd via `exec(<json>, globals())` before the
// student's own code runs. Backed by JS bridge functions on the shared Pyodide
// worker's globalThis (see ../python/pyodide.worker.js), following the same
// `import js as _js` pattern the existing GPIO shim uses.
//
// Phase 1 command surface: forward/fd, backward/bk, left/lt, right/rt,
// penup/pu, pendown/pd, pencolor, goto/setpos, setheading/seth, home,
// reset/clear, position/pos, heading, isdown. Single default turtle only —
// no Turtle() instances.
//
// Phase 2 adds: circle (built as forward/left steps — see _mark_command),
// begin_fill/end_fill/fillcolor/color, stamp, write, bgcolor, colormode.
// colormode is handled entirely here via _format_color — the JS bridge and
// engine.js only ever see final CSS-compatible color strings.
//
// `done`/`mainloop`/`bye` and a no-op `Screen()` are included as harmless stubs
// since they're near-universal turtle boilerplate that would otherwise crash a
// script for no visual reason in this headless/instant-draw model.
export const TURTLE_SHIM = [
  'import sys, types, json, math',
  'try:',
  '    import js as _js',
  'except Exception:',
  '    _js = None',
  '',
  'def _forward(distance):',
  '    if _js is not None:',
  '        _js.__hsTurtleForward(float(distance))',
  '',
  'def _turn(degrees):',
  '    if _js is not None:',
  '        _js.__hsTurtleTurn(float(degrees))',
  '',
  'def _goto(x, y):',
  '    if _js is not None:',
  '        _js.__hsTurtleGoto(float(x), float(y))',
  '',
  'def _set_heading(degrees):',
  '    if _js is not None:',
  '        _js.__hsTurtleSetHeading(float(degrees))',
  '',
  'def _home():',
  '    if _js is not None:',
  '        _js.__hsTurtleHome()',
  '',
  'def _reset():',
  '    if _js is not None:',
  '        _js.__hsTurtleReset()',
  '',
  'def _pen_up():',
  '    if _js is not None:',
  '        _js.__hsTurtlePenUp()',
  '',
  'def _pen_down():',
  '    if _js is not None:',
  '        _js.__hsTurtlePenDown()',
  '',
  'def _set_color(color):',
  '    if _js is not None:',
  '        _js.__hsTurtleSetColor(str(color))',
  '',
  'def _set_fill_color(color):',
  '    if _js is not None:',
  '        _js.__hsTurtleSetFillColor(str(color))',
  '',
  'def _set_background(color):',
  '    if _js is not None:',
  '        _js.__hsTurtleSetBackground(str(color))',
  '',
  'def _begin_fill():',
  '    if _js is not None:',
  '        _js.__hsTurtleBeginFill()',
  '',
  'def _end_fill():',
  '    if _js is not None:',
  '        _js.__hsTurtleEndFill()',
  '',
  'def _stamp():',
  '    if _js is not None:',
  '        _js.__hsTurtleStamp()',
  '    return 0',
  '',
  'def _write(text, align, font_size):',
  '    if _js is not None:',
  '        _js.__hsTurtleWrite(str(text), str(align), float(font_size))',
  '',
  'def _mark_command(name, args=None):',
  '    if _js is not None:',
  '        _js.__hsTurtleMarkCommand(str(name), json.dumps(list(args) if args else []))',
  '',
  '_colormode_state = {"mode": 255}',
  '',
  'def _format_color(value):',
  '    if isinstance(value, (tuple, list)) and len(value) == 3:',
  '        mode = _colormode_state["mode"]',
  '        if mode == 1 or mode == 1.0:',
  '            r, g, b = (max(0.0, min(1.0, float(c))) for c in value)',
  '            return "rgb({},{},{})".format(round(r * 255), round(g * 255), round(b * 255))',
  '        r, g, b = (max(0, min(255, int(c))) for c in value)',
  '        return "rgb({},{},{})".format(r, g, b)',
  '    return str(value)',
  '',
  'def _colormode(mode=None):',
  '    if mode is None:',
  '        return _colormode_state["mode"]',
  '    _colormode_state["mode"] = mode',
  '',
  'def _bgcolor(*args):',
  '    if not args:',
  '        return _get_state().get("background", "white")',
  '    color = args[0] if len(args) == 1 else args',
  '    _set_background(_format_color(color))',
  '',
  'def _get_state():',
  '    if _js is None:',
  '        return {',
  '            "x": 0.0,',
  '            "y": 0.0,',
  '            "heading": 0.0,',
  '            "penDown": True,',
  '            "color": "black",',
  '            "fillColor": "black",',
  '            "background": "white",',
  '        }',
  '    return json.loads(str(_js.__hsTurtleGetState()))',
  '',
  'class _Turtle:',
  '    def forward(self, distance):',
  '        _forward(distance)',
  '    fd = forward',
  '    def backward(self, distance):',
  '        _mark_command("backward", [distance])',
  '        _forward(-distance)',
  '    bk = backward',
  '    back = backward',
  '    def left(self, angle):',
  '        _turn(angle)',
  '    lt = left',
  '    def right(self, angle):',
  '        _turn(-angle)',
  '    rt = right',
  '    def penup(self):',
  '        _pen_up()',
  '    pu = penup',
  '    up = penup',
  '    def pendown(self):',
  '        _pen_down()',
  '    pd = pendown',
  '    down = pendown',
  '    def isdown(self):',
  '        return bool(_get_state()["penDown"])',
  '    def pencolor(self, *args):',
  '        if not args:',
  '            return _get_state()["color"]',
  '        color = args[0] if len(args) == 1 else args',
  '        _set_color(_format_color(color))',
  '    def fillcolor(self, *args):',
  '        if not args:',
  '            return _get_state().get("fillColor", "black")',
  '        color = args[0] if len(args) == 1 else args',
  '        _set_fill_color(_format_color(color))',
  '    def color(self, *args):',
  '        if not args:',
  '            return (_get_state()["color"], _get_state().get("fillColor", "black"))',
  '        if len(args) == 1:',
  '            formatted = _format_color(args[0])',
  '            _set_color(formatted)',
  '            _set_fill_color(formatted)',
  '        elif len(args) == 2:',
  '            _set_color(_format_color(args[0]))',
  '            _set_fill_color(_format_color(args[1]))',
  '        else:',
  '            formatted = _format_color(args)',
  '            _set_color(formatted)',
  '            _set_fill_color(formatted)',
  '    def begin_fill(self):',
  '        _begin_fill()',
  '    def end_fill(self):',
  '        _end_fill()',
  '    def circle(self, radius, extent=360, steps=None):',
  '        _mark_command("circle", [radius, extent])',
  '        if not radius:',
  '            return',
  '        if steps is None:',
  '            steps = max(12, min(60, int(abs(radius) / 3) + 12))',
  '        step_extent = abs(extent) / steps',
  '        step_length = 2 * abs(radius) * math.sin(math.radians(step_extent) / 2)',
  '        turn = step_extent if radius > 0 else -step_extent',
  '        for _ in range(steps):',
  '            self.forward(step_length)',
  '            self.left(turn)',
  '    def stamp(self):',
  '        return _stamp()',
  '    def write(self, text, move=False, align="left", font=("Arial", 8, "normal")):',
  '        font_size = font[1] if isinstance(font, (tuple, list)) and len(font) > 1 else 8',
  '        _write(text, align, font_size)',
  '    def goto(self, x, y=None):',
  '        if y is None:',
  '            x, y = x',
  '        _goto(x, y)',
  '    setpos = goto',
  '    setposition = goto',
  '    def setx(self, x):',
  '        _goto(x, _get_state()["y"])',
  '    def sety(self, y):',
  '        _goto(_get_state()["x"], y)',
  '    def setheading(self, angle):',
  '        _set_heading(angle)',
  '    seth = setheading',
  '    def home(self):',
  '        _home()',
  '    def reset(self):',
  '        _reset()',
  '    def clear(self):',
  '        _reset()',
  '    def position(self):',
  '        state = _get_state()',
  '        return (state["x"], state["y"])',
  '    pos = position',
  '    def xcor(self):',
  '        return _get_state()["x"]',
  '    def ycor(self):',
  '        return _get_state()["y"]',
  '    def heading(self):',
  '        return _get_state()["heading"]',
  '    def speed(self, *args, **kwargs):',
  '        pass',
  '',
  '_default_turtle = _Turtle()',
  '',
  'class _Screen:',
  '    def exitonclick(self):',
  '        pass',
  '    def title(self, *args, **kwargs):',
  '        pass',
  '    def setup(self, *args, **kwargs):',
  '        pass',
  '    def bgcolor(self, *args):',
  '        return _bgcolor(*args)',
  '    def colormode(self, mode=None):',
  '        return _colormode(mode)',
  '',
  '_default_screen = _Screen()',
  '',
  '_module = types.ModuleType("turtle")',
  'for _name in dir(_Turtle):',
  '    if not _name.startswith("_"):',
  '        setattr(_module, _name, getattr(_default_turtle, _name))',
  '_module.Screen = lambda *a, **k: _default_screen',
  '_module.done = lambda *a, **k: None',
  '_module.mainloop = lambda *a, **k: None',
  '_module.bye = lambda *a, **k: None',
  '_module.bgcolor = _bgcolor',
  '_module.colormode = _colormode',
  'sys.modules["turtle"] = _module',
].join('\n')

export function buildTurtleProgram(code) {
  return [`exec(${JSON.stringify(TURTLE_SHIM)}, globals())`, '', code].join('\n')
}
